### PR TITLE
Setup for types-2.0

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
I don't have the ability to do this (need push permission), but I'd like this to go into a new branch for the time being

### CODE REVIEW

**Comment by Diullei** [comment]
@RyanCavanaugh now your team has written permission. Could you verify?

**Comment by RyanCavanaugh** [comment]
Got it, thanks!

**Comment by use-strict** [comment]
Please see https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/144953162

**Comment by use-strict** [comment]
@RyanCavanaugh , with the fix for tsconfig paths, I now get this:
```
[Error: tsconfig.json does not exist in path /home/travis/build/DefinitelyTyped/DefinitelyTyped]
```
See https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/145853124

**Pull request closed without merging**
