### PR TITLE
change default tsc options. use `--target es6 --module commonjs --exp…

### PR DESCRIPTION
**Pull request by vvakame**
…erimentalDecorators`

### CODE REVIEW

**Comment by vvakame** [comment]
`The job exceeded the maxmimum time limit for jobs, and has been terminated.` in travis ci...

@DefinitelyTyped/contributors Can I merge this PR?
I want to use `--target es6` default in DT repo.
Promise becomes standard API and used by a lot of scene.
now, definition-tester can use `--target es6` with .tscparams, but it is not easy for understanding.
If you want to use `--target es5`, you should put .tscparams after this change released.

next step
1. release new definition-tester.
2. bump definition-tester version in DT repo & fix ci error.
3. release to master/HEAD of DT repo.

**Comment by johnnyreilly** [comment]
Fine with me

**Comment by horiuchi** [comment]
I think that's better. :+1:

**Comment by vvakame** [comment]
I'll merge this PR after dinner. (It is an hours ago)

**Comment by martine** [comment]
How do I use DefinitelyTyped definitions when targeting es5?  It seems this change caused you to drop lots of reference to Promise<>.

**Comment by alexeagle** [comment]
If you target es5 then you need to include typings like https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-promise/es6-promise.d.ts when you execute tsc.
Because of Duplicate identifiers, having these referenced from other libraries made it impossible to target --es6 due to https://github.com/Microsoft/TypeScript/issues/3215 (which is now assigned)

**Pull request merged**
